{% set name = "gcn10" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}        # [unix]
    - cmake
    - ninja
    - pkg-config               # [unix]
    - openmpi                  # [unix]
    - msmpi                    # [win]
  host:
    - openmpi                  # [unix]
    - msmpi                    # [win]
    - libgdal-core-devel
  run:
    - openmpi                  # [unix]
    - msmpi                    # [win]
    - libgdal-core

test:
  commands:
    - gcn10 --help
    - gcn10 --version
    - test -x "${PREFIX}/bin/gcn10"                    # [unix]
    - if not exist "%LIBRARY_BIN%\\gcn10.exe" exit 1  # [win]
    - where gcn10                                      # [win]

about:
  home: https://github.com/mabdazzam/gcn10
  summary: MPI-parallelized high-resolution curve number generator
  license: GPL-3.0-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - abdazzam
